/**
 * Cache contracts & invariants.
 *
 * Edge caching (Cloudflare CDN SWR) protects the platform from traffic spikes
 * and brings mobile TTFB in Algeria down from ~1200ms to ~25ms.
 *
 * Senior-dev invariants:
 *   1. High-traffic catalog & marketing pages MUST have SWR edge cache rules.
 *   2. Communes (immutable administrative data) MUST have long-lived cache.
 *   3. Transactional routes (checkout, thank-you, OTP, order submission)
 *      MUST NEVER be cached.
 *   4. Cloudflare-CDN-Cache-Control and Cache-Tag headers must be correctly
 *      generated by the Cloudflare cache provider.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import cloudflareCacheFactory from "@astrojs/cloudflare/cache/provider";

const CONFIG_PATH = resolve(__dirname, "../../astro.config.mjs");

function readConfig(): string {
  return readFileSync(CONFIG_PATH, "utf8");
}

describe("astro edge cache configuration", () => {
  const config = readConfig();

  it("configures Astro 7 native cache provider", () => {
    expect(config).toContain("cache:");
    expect(config).toContain("provider: cacheProvider");
    expect(config).toContain("@astrojs/cloudflare/cache");
  });

  it("enforces SWR cache rules for high-traffic public catalog routes", () => {
    expect(config).toContain('"/": { maxAge: 60, swr: 3600, tags: ["home"] }');
    expect(config).toContain('"/products": { maxAge: 60, swr: 3600, tags: ["products"] }');
    expect(config).toContain('"/products/[slug]": { maxAge: 60, swr: 86400, tags: ["products"] }');
    expect(config).toContain('"/category/[slug]": { maxAge: 60, swr: 86400, tags: ["categories"] }');
    expect(config).toContain('"/lp/[slug]": { maxAge: 60, swr: 86400, tags: ["landing-pages"] }');
  });

  it("enforces long-lived cache for legal pages and immutable communes", () => {
    expect(config).toContain('"/pages/[slug]": { maxAge: 3600, swr: 604800, tags: ["legal-pages"] }');
    expect(config).toContain('"/api/communes/[wilayaId]": { maxAge: 31536000, swr: 31536000, tags: ["communes"] }');
  });

  it("strictly excludes transactional surfaces from routeRules (never cache money/PII/OTP)", () => {
    const routeRulesMatch = config.match(/routeRules:\s*\{([^}]+)\}/s);
    expect(routeRulesMatch).not.toBeNull();
    const rules = routeRulesMatch![1];

    // Must never contain checkout, thank-you, or sensitive API routes
    expect(rules).not.toContain('"/checkout"');
    expect(rules).not.toContain('"/thank-you"');
    expect(rules).not.toContain('"/api/otp"');
    expect(rules).not.toContain('"/api/abandoned"');
    expect(rules).not.toContain('"/api/cart/validate"');
  });
});

describe("cloudflare cache provider header contract", () => {
  const provider = cloudflareCacheFactory(undefined);

  it("generates Cloudflare-CDN-Cache-Control with SWR for products", () => {
    const req = new Request("https://demo.codflow.store/products/wireless-earbuds");
    const headers = provider.setHeaders!(
      { maxAge: 60, swr: 86400, tags: ["products"] },
      req
    );

    expect(headers.get("Cloudflare-CDN-Cache-Control")).toBe(
      "public, max-age=60, stale-while-revalidate=86400"
    );
    expect(headers.get("Cache-Tag")).toContain("products");
    expect(headers.get("Cache-Tag")).toContain("astro-path:/products/wireless-earbuds");
  });

  it("generates Cloudflare-CDN-Cache-Control with SWR for landing pages", () => {
    const req = new Request("https://demo.codflow.store/lp/exclusive-deal");
    const headers = provider.setHeaders!(
      { maxAge: 60, swr: 86400, tags: ["landing-pages"] },
      req
    );

    expect(headers.get("Cloudflare-CDN-Cache-Control")).toBe(
      "public, max-age=60, stale-while-revalidate=86400"
    );
    expect(headers.get("Cache-Tag")).toContain("landing-pages");
    expect(headers.get("Cache-Tag")).toContain("astro-path:/lp/exclusive-deal");
  });

  it("generates immutable cache headers for Algerian communes", () => {
    const req = new Request("https://demo.codflow.store/api/communes/16");
    const headers = provider.setHeaders!(
      { maxAge: 31536000, swr: 31536000, tags: ["communes"] },
      req
    );

    expect(headers.get("Cloudflare-CDN-Cache-Control")).toBe(
      "public, max-age=31536000, stale-while-revalidate=31536000"
    );
    expect(headers.get("Cache-Tag")).toContain("communes");
    expect(headers.get("Cache-Tag")).toContain("astro-path:/api/communes/16");
  });
});
